default: &default
  adapter: postgresql
  encoding: unicode
  username: 
  password: ife
  pool: 5
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: blog

test:
  <<: *default
  database: your_test_database_name

production:
  <<: *default
  database: your__prod_database_name